---
- hosts: webservers
  become: true
  tasks:
    - name: create a user
      user:
        name=nandu password=admi1234 groups=ec2-user 
    - name: Uninstall User
      user: 
        name=nandu state=absent remove=yes forse=yes 
